const assert = require('node:assert/strict');
const fs = require('node:fs');
assert.ok(fs.existsSync(__dirname + '/../pricing.js'), 'pricing module must exist');
const p = require('../pricing.js');
const a = require('../attribution.js');
const expected = {weekday:{esports:[180,490,870,800,540],comfort:[200,540,960,800,600]},weekend:{esports:[200,540,960,800,600],comfort:[220,600,1060,800,660]}};
let cases = 0;
for(const day of Object.keys(expected)) for(const hall of Object.keys(expected[day])) ['hour','three','six','night','morning'].forEach((duration,i)=>{assert.equal(p.quote(day,hall,duration).price,expected[day][hall][i]); cases++;});
assert.equal(p.quote('weekday','ps5','hour'),null);
assert.equal(p.quote('bad','esports','hour'),null);
assert.equal(p.quote('weekday','esports','night').hours,12);
assert.equal(p.quote('weekday','esports','morning').hours,5);
const now=1800000000000;
const old={at:now-1000,params:{utm_source:'yandex',yclid:'old'}};
assert.deepEqual(a.resolve('?utm_source=vk&rb_clickid=new',old,now).params,{utm_source:'vk',rb_clickid:'new'});
assert.deepEqual(a.resolve('',old,now).params,old.params);
assert.deepEqual(a.resolve('',{...old,at:now-31*86400000},now).params,{});
assert.deepEqual(a.resolve('?password=secret&foo=bar',null,now).params,{});
assert.deepEqual(a.resolve('',{at:now,params:{password:'secret',utm_source:'vk'}},now).params,{utm_source:'vk'});
assert.equal(a.resolve('?utm_source='+ 'x'.repeat(500),null,now).params.utm_source.length,300);
const b=new URL(a.bookingURL('https://langame.ru/example/booking',old.params,'B'));
assert.equal(b.searchParams.get('arena_variant'),'B');assert.equal(b.searchParams.get('yclid'),'old');
console.log('PASS:',cases,'tariff combinations + 11 attribution/edge checks');
